 
[build]
  base = "/" # Specify the base directory
  publish = "airline_management_system/" # Specify the publish directory
   command = "gunicorn -b :$PORT app:app" # Specify the build command using Gunicorn
